header:
    title: Pratical Numerology Solutions
    text: NumeroYogi
    button: Tell Me More
    buttonlink: "#services"

services:
    title: "Reach Us"
    text: "Join us today to know more"
    section: services
    list:
      - title: "[Facebook](https://numeroyogi.co.in)"
        desc: "Our very own facebook page where you can find others, discuss, ask questions and stay connected to us."
        icon: fab fa-facebook-f #find more at https://fontawesome.com/icons
      - title: "[Blog](https://numeroyogi.co.in)"
        desc: "Numeroyogi blog where you can find our expert analysis, discussion and more on numerology, astrology, hypnosis and more."
        icon: fas fa-blog
      - title: "[Whatsapp](https://numeroyogi.co.in)"
        desc: "Our very own whatsapp groip where you can get in direct touch with our experts, hear other peoples stories or tell on of your own."
        icon: fab fa-whatsapp

portfolio:
    title: "What We Do?"
    text: "Extensive Research in the diverse fields of occult sciences i.e. Numerology, Astrology, Hypnosis and more."
    section: portfolio
    closebutton: "Go Back"


timeline:
    title: "About"
    text: "Who we are?"
    section: timeline
    # left is the default
    #start_align: "left"
    events:
      - title: "Our Website"
        year: "About the website"
        desc: "NumeroYogi website is owned and developed for the purpose of extensive researches in the diverse fields of occult sciences i.e. Numerology, Astrology, Palmistry and Hypnosis. The owner of NumeroYogi has been researching in the field of occult sciences, particularly in Astrology and Numerology for last 20 years and intend to use these mystic sciences for the service of humanity."
        image: assets/img/timeline/1.jpg
        alt:
      - title: "Coming Together"
        year: "About our team"
        desc: "NumeroYogi Team is a group of progressive occult practitioners and researchers, who believe in comprehensive, pragmatic, logical and scientific findings in the Numerology based on its all-encompassing database of thousands of birth details, recorded events, patterns and conclusive findings.."
        image: assets/img/timeline/4.jpg
        align: right
      - title: "Objective"
        year: "What we want to acheive?"
        desc: "The intent, object and vision of NumeroYogi is to spread the real knowledge of the occult sciences, particularly Numerology and Astrology besides letting the World know about the richness of the great treasure of the wonderful mystic-sciences. The researches and findings of NumeroYogi are copyrighted exclusively owned by NumeroYogi © and shall be published time to time on this website for the benefit of the World and humanity..."
        image: assets/img/timeline/1.jpg
        alt:
        alt:
        # you can enforce the aligment
    end: "Be Part <br> of Our <br> Journey!"

team:
    title: "OUR AMAZING TEAM"
    text: "Experts in their respective Feilds."
    subtext: Know more about our team and contact us directly if you have any questions.
    section: team
    people:
      - name: "Astrologer"
        role: ""
        image: assets/img/team/500x500.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "Hypnotist"
        role: ""
        image: assets/img/team/500x500.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "Numerologist"
        role: ""
        image: assets/img/team/500x500.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in

contact:
    title: "Contact Us"
    text: "Ask Away all of your questions!!"
    section: contact

footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com
        icon: "fab fa-twitter"
      - url: https://facebook.com
        icon: "fab fa-facebook-f"
      - url: https://linkedin.com
        icon: "fab fa-linkedin-in"
      - url: https://github.com/raviriley/agency-jekyll-theme
        icon: "fab fa-github"
      - url: https://instagram.com
        icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
